In [2]:
from scipy.io import loadmat
import polars as pl
import numpy as np
from pathlib import Path

In [9]:
for p in Path().glob('*.mat'):
    print(p)
    data = loadmat(p)
    in_extraction = data['in_extraction']
    out_extraction = data['out_extraction']
    extraction = np.concatenate((in_extraction.real, in_extraction.imag, out_extraction.real, out_extraction.imag), axis=1)
    newfile = f'{p.stem}_extraction.csv'
    pl.DataFrame(extraction, columns=('in_real', 'in_imag', 'out_real', 'out_imag')).write_csv(newfile)

    in_validation = data['in_validation']
    out_validation = data['out_validation']
    validation = np.concatenate((in_validation.real, in_validation.imag, out_validation.real, out_validation.imag), axis=1)
    newfile = f'{p.stem}_validation.csv'
    pl.DataFrame(extraction, columns=('in_real', 'in_imag', 'out_real', 'out_imag')).write_csv(newfile)

modeledsbrt.mat
modeleddoherty.mat
modeledADSdata.mat
modeledcadence.mat


In [11]:
def load_csv2numpy(p):
    return np.loadtxt(p, delimiter=',', dtype=np.float32, skiprows=1)

for p in Path().glob('*.csv'):
    print(p)
    print(load_csv2numpy(p)[:10])

modeledcadence_extraction.csv
[[ 8.6949341e-04  2.6527445e-03 -1.7157222e-01  1.5471938e-01]
 [ 2.0818049e-04  4.5616915e-03 -3.5212654e-01  1.7175931e-01]
 [-7.0258387e-04  6.1117331e-03 -5.1363164e-01  1.5640546e-01]
 [-1.6773941e-03  7.0649432e-03 -6.3123721e-01  1.1484120e-01]
 [-2.4939207e-03  7.2282506e-03 -6.8143851e-01  5.7876058e-02]
 [-2.9424194e-03  6.4894753e-03 -6.4683449e-01 -1.8229589e-03]
 [-2.8816974e-03  4.8317583e-03 -5.1955158e-01 -5.3340789e-02]
 [-2.2484032e-03  2.3514510e-03 -3.0289796e-01 -8.8169247e-02]
 [-1.0645824e-03 -7.5609208e-04 -9.2618586e-03 -1.0105909e-01]
 [ 5.7932851e-04 -4.2186589e-03  3.3012605e-01 -8.9033104e-02]]
modeledsbrt_extraction.csv
[[ 0.09581241  0.33332708  0.1386929   0.43440637]
 [ 0.40478685  0.21613574  0.4841552   0.2731053 ]
 [ 0.6565765   0.07603001  0.7056862   0.08675913]
 [ 0.85250455 -0.08307808  0.7850607  -0.07499877]
 [ 0.96412873 -0.23170502  0.79936546 -0.1728798 ]
 [ 0.98543715 -0.37057194  0.83030456 -0.2772701 ]
 [ 0.9